# Experiment 14 EDA 01/04/2026
### Name : Tanmay Agarwal
### PRN : 25070123158
### Batch : EnTC A3
### Title: Data Normalization and Turning Categorical Variables into Quantitative Variables in Python

In [2]:
#Dataset
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8]
}

df=pd.DataFrame(data)
df

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [4]:
#1. Min-Max Normalization
#Min-Max Normalization for Price

df['Price_MinMax']= (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price")
(df[['Product','Price','Price_MinMax']])

Min-Max Normalized Price

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [13]:
#2. Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
df

      Product  Price  Units_Sold  Discount  Price_MinMax  Units_Zscore
0      Laptop  55000          25        10      1.000000     -0.799885
1      Mobile  20000          60        15      0.339623      0.660775
2      Tablet  30000          35        12      0.528302     -0.382554
3  Headphones   2000          80        20      0.000000      1.495437
4  Smartwatch   8000          50        18      0.113208      0.243443
5      Camera  45000          15         8      0.811321     -1.217216

In [16]:
#3.Decimal Scaling

df['Price_decimal'] = df['Price'] / 100000 #(10^5)

df

,Product,Price,Units_Sold,Discount,Price_MinMax,Units_Zscore,Price_decimal
0,Laptop,55000,25,10,1.000000,-0.799885,0.55
1,Mobile,20000,60,15,0.339623,0.660775,0.20
2,Tablet,30000,35,12,0.528302,-0.382554,0.30
3,Headphones,2000,80,20,0.000000,1.495437,0.02
4,Smartwatch,8000,50,18,0.113208,0.243443,0.08
5,Camera,45000,15,8,0.811321,-1.217216,0.45

In [7]:
#Normalize Multiple Columns
cols = ['Price','Units_Sold','Discount']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

#Part B- Turning Categorical Variables into Quantitative Variables in Python

In [18]:
data = {
    'Order ID': [101, 102, 103, 104, 105, 106],
    'Customer_Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    "Payment_Method": ['Credit Card', 'PayPal', 'Credit Card', 'PayPal', 'Credit Card', 'PayPal'],
    'Product-category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'City':['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Miami', 'Seattle'],
    'Order_value': [1500, 800, 2000, 1667, 12788, 7756]
}

df1=pd.DataFrame(data)
df1

,Order ID,Customer_Gender,Payment_Method,Product-category,City,Order_value
0,101,Male,Credit Card,Electronics,New York,1500
1,102,Female,PayPal,Clothing,Los Angeles,800
2,103,Male,Credit Card,Electronics,Chicago,2000
3,104,Female,PayPal,Clothing,San Francisco,1667
4,105,Male,Credit Card,Electronics,Miami,12788
5,106,Female,PayPal,Clothing,Seattle,7756

In [20]:
#Method 1: Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df1['Gender_Label'] = le.fit_transform(df1['Customer_Gender'])

df1

,Order ID,Customer_Gender,Payment_Method,Product-category,City,Order_value,Gender_Label
0,101,Male,Credit Card,Electronics,New York,1500,1
1,102,Female,PayPal,Clothing,Los Angeles,800,0
2,103,Male,Credit Card,Electronics,Chicago,2000,1
3,104,Female,PayPal,Clothing,San Francisco,1667,0
4,105,Male,Credit Card,Electronics,Miami,12788,1
5,106,Female,PayPal,Clothing,Seattle,7756,0

In [24]:
#Method 2: One Hot Encoding

df_encoded = pd.get_dummies(df1, columns=['Payment_Method'])

df_encoded

,Order ID,Customer_Gender,Product-category,City,Order_value,Gender_Label,Payment_Method_Credit Card,Payment_Method_PayPal
0,101,Male,Electronics,New York,1500,1,True,False
1,102,Female,Clothing,Los Angeles,800,0,False,True
2,103,Male,Electronics,Chicago,2000,1,True,False
3,104,Female,Clothing,San Francisco,1667,0,False,True
4,105,Male,Electronics,Miami,12788,1,True,False
5,106,Female,Clothing,Seattle,7756,0,False,True

In [25]:
#Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df1, columns=['Payment_Method'], drop_first=True)

df_dummy

,Order ID,Customer_Gender,Product-category,City,Order_value,Gender_Label,Payment_Method_PayPal
0,101,Male,Electronics,New York,1500,1,False
1,102,Female,Clothing,Los Angeles,800,0,True
2,103,Male,Electronics,Chicago,2000,1,False
3,104,Female,Clothing,San Francisco,1667,0,True
4,105,Male,Electronics,Miami,12788,1,False
5,106,Female,Clothing,Seattle,7756,0,True

#New Dataset Operations (Amazon)

In [37]:
#Data Normalization
import pandas as pd
df=pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

In [38]:
#1. Min-Max Normalization
#Min-Max Normalization for Price

df['Price_MinMax']= (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price")
(df[['Product_Name','Price','Price_MinMax']])

Min-Max Normalized Price

                   Product_Name  Price  Price_MinMax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

In [43]:
#Min-Max Normalization for Rating

df['Rating_MinMax']= (df['Rating'] - df['Rating'].min()) / (df['Rating'].max() - df['Rating'].min())
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Zscore,Price_decimal,Rating_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.812282,0.00799,0.428571
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,-0.260855,0.01499,0.714286
2,P103,USB Keyboard,699,4.1,870,180,0.016194,-0.591051,0.00699,0.142857
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,1.307576,0.02499,0.857143
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,2.215615,0.03999,0.571429
5,P106,Power Bank,1199,4.2,1750,390,0.036437,1.142478,0.01199,0.285714
6,P107,Laptop Stand,899,4.0,620,140,0.024291,-0.921247,0.00899,0.000000
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.069341,0.01899,0.428571
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.647184,0.05499,1.000000
9,P110,Wireless Charger,999,4.2,760,190,0.028340,-0.508502,0.00999,0.285714
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,2.958556,0.07999,0.857143
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.316988,0.04599,0.714286
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.729733,0.01599,0.571429
13,P114,Tablet Stand,699,4.1,540,120,0.016194,-1.086345,0.00699,0.142857
14,P115,USB Hub,899,4.2,870,200,0.024291,-0.425953,0.00899,0.285714
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.482086,0.06499,0.857143
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,-0.343404,0.01199,0.428571
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,1.390125,0.01999,0.571429
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,2.298164,0.02999,0.714286
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.069341,0.01299,0.428571
20,P121,Phone Holder,499,4.0,420,150,0.008097,-0.838698,0.00499,0.000000
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.482086,0.02499,0.571429
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,-0.673600,0.08999,0.857143
23,P124,Smart Plug,799,4.2,720,210,0.020243,-0.343404,0.00799,0.285714
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,1.142478,0.03499,0.714286
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,-0.756149,0.04599,0.571429
26,P127,VR Headset,12999,4.7,3100,140,0.514170,-0.921247,0.12999,1.000000
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.151890,0.02199,0.428571
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,-0.095757,0.00699,0.285714
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.069341,0.01499,0.428571
30,P131,Action Camera,9999,4.6,2100,200,0.392713,-0.425953,0.09999,0.857143
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,-0.591051,0.05999,0.714286
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,1.472674,0.03499,0.571429
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,-1.086345,0.11999,0.857143
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,-1.333992,0.15999,1.000000
35,P136,Desk Organizer,599,4.1,450,160,0.012146,-0.756149,0.00599,0.142857
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.564635,0.00799,0.285714
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,1.059929,0.00299,0.000000
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,-0.343404,0.00999,0.428571
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,-1.003796,0.01499,0.571429
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,-0.838698,0.02999,0.714286
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,-1.168894,0.10999,0.857143
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.069341,0.04999,0.571429
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,-1.499090,0.24999,1.000000
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.482086,0.01999,0.428571
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,-0.425953,0.07999,0.857143
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,-1.086345,0.18999,0.714286
47,P148,Smart Scale,2499,4.4,980,170,0.089069,-0.673600,0.02499,0.571429
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,-0.838698,0.03499,0.428571
49,P150,Portable Fan,999,4.2,760,240,0.028340,-0.095757,0.00999,0.285714

In [44]:
#2. Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Zscore,Price_decimal,Rating_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.812282,0.00799,0.428571
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,-0.260855,0.01499,0.714286
2,P103,USB Keyboard,699,4.1,870,180,0.016194,-0.591051,0.00699,0.142857
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,1.307576,0.02499,0.857143
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,2.215615,0.03999,0.571429
5,P106,Power Bank,1199,4.2,1750,390,0.036437,1.142478,0.01199,0.285714
6,P107,Laptop Stand,899,4.0,620,140,0.024291,-0.921247,0.00899,0.000000
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.069341,0.01899,0.428571
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.647184,0.05499,1.000000
9,P110,Wireless Charger,999,4.2,760,190,0.028340,-0.508502,0.00999,0.285714
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,2.958556,0.07999,0.857143
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.316988,0.04599,0.714286
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.729733,0.01599,0.571429
13,P114,Tablet Stand,699,4.1,540,120,0.016194,-1.086345,0.00699,0.142857
14,P115,USB Hub,899,4.2,870,200,0.024291,-0.425953,0.00899,0.285714
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.482086,0.06499,0.857143
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,-0.343404,0.01199,0.428571
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,1.390125,0.01999,0.571429
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,2.298164,0.02999,0.714286
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.069341,0.01299,0.428571
20,P121,Phone Holder,499,4.0,420,150,0.008097,-0.838698,0.00499,0.000000
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.482086,0.02499,0.571429
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,-0.673600,0.08999,0.857143
23,P124,Smart Plug,799,4.2,720,210,0.020243,-0.343404,0.00799,0.285714
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,1.142478,0.03499,0.714286
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,-0.756149,0.04599,0.571429
26,P127,VR Headset,12999,4.7,3100,140,0.514170,-0.921247,0.12999,1.000000
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.151890,0.02199,0.428571
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,-0.095757,0.00699,0.285714
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.069341,0.01499,0.428571
30,P131,Action Camera,9999,4.6,2100,200,0.392713,-0.425953,0.09999,0.857143
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,-0.591051,0.05999,0.714286
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,1.472674,0.03499,0.571429
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,-1.086345,0.11999,0.857143
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,-1.333992,0.15999,1.000000
35,P136,Desk Organizer,599,4.1,450,160,0.012146,-0.756149,0.00599,0.142857
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.564635,0.00799,0.285714
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,1.059929,0.00299,0.000000
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,-0.343404,0.00999,0.428571
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,-1.003796,0.01499,0.571429
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,-0.838698,0.02999,0.714286
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,-1.168894,0.10999,0.857143
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.069341,0.04999,0.571429
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,-1.499090,0.24999,1.000000
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.482086,0.01999,0.428571
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,-0.425953,0.07999,0.857143
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,-1.086345,0.18999,0.714286
47,P148,Smart Scale,2499,4.4,980,170,0.089069,-0.673600,0.02499,0.571429
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,-0.838698,0.03499,0.428571
49,P150,Portable Fan,999,4.2,760,240,0.028340,-0.095757,0.00999,0.285714

In [45]:
#3.Decimal Scaling

df['Price_decimal'] = df['Price'] / 100000 #(10^5)

df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Units_Zscore,Price_decimal,Rating_MinMax
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.812282,0.00799,0.428571
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,-0.260855,0.01499,0.714286
2,P103,USB Keyboard,699,4.1,870,180,0.016194,-0.591051,0.00699,0.142857
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,1.307576,0.02499,0.857143
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,2.215615,0.03999,0.571429
5,P106,Power Bank,1199,4.2,1750,390,0.036437,1.142478,0.01199,0.285714
6,P107,Laptop Stand,899,4.0,620,140,0.024291,-0.921247,0.00899,0.000000
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.069341,0.01899,0.428571
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,0.647184,0.05499,1.000000
9,P110,Wireless Charger,999,4.2,760,190,0.028340,-0.508502,0.00999,0.285714
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,2.958556,0.07999,0.857143
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.316988,0.04599,0.714286
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.729733,0.01599,0.571429
13,P114,Tablet Stand,699,4.1,540,120,0.016194,-1.086345,0.00699,0.142857
14,P115,USB Hub,899,4.2,870,200,0.024291,-0.425953,0.00899,0.285714
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.482086,0.06499,0.857143
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,-0.343404,0.01199,0.428571
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,1.390125,0.01999,0.571429
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,2.298164,0.02999,0.714286
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.069341,0.01299,0.428571
20,P121,Phone Holder,499,4.0,420,150,0.008097,-0.838698,0.00499,0.000000
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.482086,0.02499,0.571429
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,-0.673600,0.08999,0.857143
23,P124,Smart Plug,799,4.2,720,210,0.020243,-0.343404,0.00799,0.285714
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,1.142478,0.03499,0.714286
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,-0.756149,0.04599,0.571429
26,P127,VR Headset,12999,4.7,3100,140,0.514170,-0.921247,0.12999,1.000000
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.151890,0.02199,0.428571
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,-0.095757,0.00699,0.285714
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.069341,0.01499,0.428571
30,P131,Action Camera,9999,4.6,2100,200,0.392713,-0.425953,0.09999,0.857143
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,-0.591051,0.05999,0.714286
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,1.472674,0.03499,0.571429
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,-1.086345,0.11999,0.857143
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,-1.333992,0.15999,1.000000
35,P136,Desk Organizer,599,4.1,450,160,0.012146,-0.756149,0.00599,0.142857
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.564635,0.00799,0.285714
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,1.059929,0.00299,0.000000
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,-0.343404,0.00999,0.428571
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,-1.003796,0.01499,0.571429
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,-0.838698,0.02999,0.714286
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,-1.168894,0.10999,0.857143
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.069341,0.04999,0.571429
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,-1.499090,0.24999,1.000000
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.482086,0.01999,0.428571
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,-0.425953,0.07999,0.857143
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,-1.086345,0.18999,0.714286
47,P148,Smart Scale,2499,4.4,980,170,0.089069,-0.673600,0.02499,0.571429
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,-0.838698,0.03499,0.428571
49,P150,Portable Fan,999,4.2,760,240,0.028340,-0.095757,0.00999,0.285714

In [46]:
#Converting Data Types
import pandas as pd
df=pd.read_csv("/content/Student-Dataset.csv")

In [48]:
#Label Encoding- Placement Status
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Placement_Label'] = le.fit_transform(df['Placement_Status'])

df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,1
1,102,Male,IT,7.5,1,85,Not Placed,0,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,0
4,105,Female,Computer,8.7,0,88,Placed,480000,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,0
6,107,Female,IT,8.9,0,91,Placed,500000,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,0

In [49]:
#One-Hot Encoding- Department

df_encoded = pd.get_dummies(df, columns=['Department'])

df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,False,True

In [51]:
#Dummies- Department
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

df_dummy

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Placement_Label,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,0,False,False,False,True